- examples/todo/package-lock.json
- examples/todo/package.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.25.1-canary.4.a1d2f8aaa268f186ef3b88535431acde19865d13.0
npm install @salutejs/recognizer-string-similarity@0.25.1-canary.4.a1d2f8aaa268f186ef3b88535431acde19865d13.0
npm install @salutejs/scenario@0.25.1-canary.4.a1d2f8aaa268f186ef3b88535431acde19865d13.0
npm install @salutejs/storage-adapter-firebase@0.25.1-canary.4.a1d2f8aaa268f186ef3b88535431acde19865d13.0
npm install @salutejs/storage-adapter-memory@0.25.1-canary.4.a1d2f8aaa268f186ef3b88535431acde19865d13.0
yarn add @salutejs/recognizer-smartapp-brain@0.25.1-canary.4.a1d2f8aaa268f186ef3b88535431acde19865d13.0
yarn add …
```
> Не запускается examples/todo

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.26.0-canary.5.500cf9fc091e88419c65160347c1a02e29493984.0
npm install @salutejs/recognizer-string-similarity@0.26.0-canary.5.500cf9fc091e88419c65160347c1a02e29493984.0
npm install @salutejs/scenario@0.26.0-canary.5.500cf9fc091e88419c65160347c1a02e29493984.0
npm install @salutejs/storage-adapter-firebase@0.26.0-canary.5.500cf9fc091e88419c65160347c1a02e29493984.0
npm install @salutejs/storage-adapter-memory@0.26.0-canary.5.500cf9fc091e88419c65160347c1a02e29493984.0
yarn add @salutejs/recognizer-smartapp-brain@0.26.0-canary.5.500cf9fc091e88419c65160347c1a02e29493984.0
yarn add …
```
> feat: Обновлён тип AppInfo

- .github/workflows/release.yml
- package-lock.json
- package.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.25.1-canary.7.2395426948.0
npm install @salutejs/recognizer-string-similarity@0.25.1-canary.7.2395426948.0
npm install @salutejs/scenario@0.25.1-canary.7.2395426948.0
npm install @salutejs/storage-adapter-firebase@0.25.1-canary.7.2395426948.0
npm install @salutejs/storage-adapter-memory@0.25.1-canary.7.2395426948.0
yarn add @salutejs/recognizer-smartapp-brain@0.25.1-canary.7.2395426948.0
yarn add @salutejs/recognizer-string-similarity@0.25.1-canary.7.2395426948.0
yarn add @salutejs/scenario@0.25.1-canary.7.2395426948.0
yarn add @salutejs/storage-adapter-firebase@0.25.1-canary.7.2395426948.0 …
```
> обновление auto

- packages/recognizer-smartapp-brain/package.json
- packages/recognizer-string-similarity/package.json
- packages/scenario/package.json
- packages/storage-adapter-firebase/package.json
- packages/storage-adapter-memory/package.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.25.1-canary.8.2396056396.0
npm install @salutejs/recognizer-string-similarity@0.25.1-canary.8.2396056396.0
npm install @salutejs/scenario@0.25.1-canary.8.2396056396.0
npm install @salutejs/storage-adapter-firebase@0.25.1-canary.8.2396056396.0
npm install @salutejs/storage-adapter-memory@0.25.1-canary.8.2396056396.0
yarn add @salutejs/recognizer-smartapp-brain@0.25.1-canary.8.2396056396.0
yarn add @salutejs/recognizer-string-similarity@0.25.1-canary.8.2396056396.0
yarn add @salutejs/scenario@0.25.1-canary.8.2396056396.0
yarn add @salutejs/storage-adapter-firebase@0.25.1-canary.8.2396056396.0 …
```
> Убрал gitHead

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.26.2-canary.13.2917402637.0
npm install @salutejs/recognizer-string-similarity@0.26.2-canary.13.2917402637.0
npm install @salutejs/scenario@0.26.2-canary.13.2917402637.0
npm install @salutejs/storage-adapter-firebase@0.26.2-canary.13.2917402637.0
npm install @salutejs/storage-adapter-memory@0.26.2-canary.13.2917402637.0
yarn add @salutejs/recognizer-smartapp-brain@0.26.2-canary.13.2917402637.0
yarn add @salutejs/recognizer-string-similarity@0.26.2-canary.13.2917402637.0
yarn add @salutejs/scenario@0.26.2-canary.13.2917402637.0
yarn add …
```
> Типизация discovery_card

- packages/scenario/src/lib/createSaluteResponse.ts
- packages/scenario/src/lib/types/response.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.26.3-canary.15.3097890964.0
npm install @salutejs/recognizer-string-similarity@0.26.3-canary.15.3097890964.0
npm install @salutejs/scenario@0.26.3-canary.15.3097890964.0
npm install @salutejs/storage-adapter-firebase@0.26.3-canary.15.3097890964.0
npm install @salutejs/storage-adapter-memory@0.26.3-canary.15.3097890964.0
yarn add @salutejs/recognizer-smartapp-brain@0.26.3-canary.15.3097890964.0
yarn add @salutejs/recognizer-string-similarity@0.26.3-canary.15.3097890964.0
yarn add @salutejs/scenario@0.26.3-canary.15.3097890964.0
yarn add …
```
> Заполнять поле framework_type в ответе

- packages/scenario/src/lib/createSaluteResponse.ts
- packages/scenario/src/lib/types/salute.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.27.2-canary.22.3329550374.0
npm install @salutejs/recognizer-string-similarity@0.27.2-canary.22.3329550374.0
npm install @salutejs/scenario@0.27.2-canary.22.3329550374.0
npm install @salutejs/storage-adapter-firebase@0.27.2-canary.22.3329550374.0
npm install @salutejs/storage-adapter-memory@0.27.2-canary.22.3329550374.0
yarn add @salutejs/recognizer-smartapp-brain@0.27.2-canary.22.3329550374.0
yarn add @salutejs/recognizer-string-similarity@0.27.2-canary.22.3329550374.0
yarn add @salutejs/scenario@0.27.2-canary.22.3329550374.0
yarn add …
```
> Не только type/payload в appendCommand

- packages/scenario/src/lib/createSaluteResponse.ts
- packages/scenario/src/lib/types/response.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.28.0-canary.24.3703917855.0
npm install @salutejs/recognizer-string-similarity@0.28.0-canary.24.3703917855.0
npm install @salutejs/scenario@0.28.0-canary.24.3703917855.0
npm install @salutejs/storage-adapter-firebase@0.28.0-canary.24.3703917855.0
npm install @salutejs/storage-adapter-memory@0.28.0-canary.24.3703917855.0
yarn add @salutejs/recognizer-smartapp-brain@0.28.0-canary.24.3703917855.0
yarn add @salutejs/recognizer-string-similarity@0.28.0-canary.24.3703917855.0
yarn add @salutejs/scenario@0.28.0-canary.24.3703917855.0
yarn add …
```
> Опциональное поле intent в ответе

- packages/scenario/src/lib/createSaluteRequest.ts
- packages/scenario/src/lib/createScenarioWalker.ts
- packages/scenario/src/lib/types/request.ts
Closes #29 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.29.1-canary.30.3929885342.0
npm install @salutejs/recognizer-string-similarity@0.29.1-canary.30.3929885342.0
npm install @salutejs/scenario@0.29.1-canary.30.3929885342.0
npm install @salutejs/storage-adapter-firebase@0.29.1-canary.30.3929885342.0
npm install @salutejs/storage-adapter-memory@0.29.1-canary.30.3929885342.0
yarn add @salutejs/recognizer-smartapp-brain@0.29.1-canary.30.3929885342.0
yarn add @salutejs/recognizer-string-similarity@0.29.1-canary.30.3929885342.0
yarn add @salutejs/scenario@0.29.1-canary.30.3929885342.0
yarn add …
```
> Не работает response.voiceAction

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.31.0-canary.32.4142493179.0
npm install @salutejs/recognizer-string-similarity@0.31.0-canary.32.4142493179.0
npm install @salutejs/scenario@0.31.0-canary.32.4142493179.0
npm install @salutejs/storage-adapter-firebase@0.31.0-canary.32.4142493179.0
npm install @salutejs/storage-adapter-memory@0.31.0-canary.32.4142493179.0
yarn add @salutejs/recognizer-smartapp-brain@0.31.0-canary.32.4142493179.0
yarn add @salutejs/recognizer-string-similarity@0.31.0-canary.32.4142493179.0
yarn add @salutejs/scenario@0.31.0-canary.32.4142493179.0
yarn add …
```
> Добавлена типизация transfer_to_operator

- packages/scenario/src/lib/createScenarioWalker.ts
Closes #35 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.30.1-canary.36.4131924518.0
npm install @salutejs/recognizer-string-similarity@0.30.1-canary.36.4131924518.0
npm install @salutejs/scenario@0.30.1-canary.36.4131924518.0
npm install @salutejs/storage-adapter-firebase@0.30.1-canary.36.4131924518.0
npm install @salutejs/storage-adapter-memory@0.30.1-canary.36.4131924518.0
yarn add @salutejs/recognizer-smartapp-brain@0.30.1-canary.36.4131924518.0
yarn add @salutejs/recognizer-string-similarity@0.30.1-canary.36.4131924518.0
yarn add @salutejs/scenario@0.30.1-canary.36.4131924518.0
yarn add …
```
> Асинхронные обработчики SystemScenario

- examples/todo/next-env.d.ts
- examples/todo/package-lock.json
- examples/todo/package.json
- packages/scenario/src/lib/createSaluteResponse.ts
- packages/scenario/src/lib/types/response.ts
- packages/scenario/src/lib/types/salute.ts
Closes #37 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.32.0-canary.38.4426649967.0
npm install @salutejs/recognizer-string-similarity@0.32.0-canary.38.4426649967.0
npm install @salutejs/scenario@0.32.0-canary.38.4426649967.0
npm install @salutejs/storage-adapter-firebase@0.32.0-canary.38.4426649967.0
npm install @salutejs/storage-adapter-memory@0.32.0-canary.38.4426649967.0
yarn add @salutejs/recognizer-smartapp-brain@0.32.0-canary.38.4426649967.0
yarn add @salutejs/recognizer-string-similarity@0.32.0-canary.38.4426649967.0
yarn add @salutejs/scenario@0.32.0-canary.38.4426649967.0
yarn add …
```
> Добавить поле в ответ

- examples/audiotour/package-lock.json
- examples/audiotour/package.json
- examples/audiotour/src/app.ts
- examples/chatapp-brain/package-lock.json
- examples/chatapp-brain/package.json
- examples/chatapp-brain/src/index.ts
- examples/chatapp-brain/src/middleware.ts
- examples/echo/package-lock.json
- examples/echo/package.json
- examples/echo/src/server.ts
- examples/payment-chatapp/package-lock.json
- examples/payment-chatapp/package.json
- examples/payment-chatapp/src/index.ts
- examples/todo/package-lock.json
- examples/todo/package.json
- examples/todo/src/pages/api/hook.ts
- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.32.1-canary.39.4437520548.0
npm install @salutejs/recognizer-string-similarity@0.32.1-canary.39.4437520548.0
npm install @salutejs/scenario@0.32.1-canary.39.4437520548.0
npm install @salutejs/storage-adapter-firebase@0.32.1-canary.39.4437520548.0
npm install @salutejs/storage-adapter-memory@0.32.1-canary.39.4437520548.0
yarn add @salutejs/recognizer-smartapp-brain@0.32.1-canary.39.4437520548.0
yarn add @salutejs/recognizer-string-similarity@0.32.1-canary.39.4437520548.0
yarn add @salutejs/scenario@0.32.1-canary.39.4437520548.0
yarn add …
```
> messageId это bigint

- .huskyrc.json
- examples/payment-chatapp/src/handlers.ts
- packages/scenario/README.md
- packages/scenario/src/lib/createSaluteRequest.ts
- packages/scenario/src/lib/createScenarioWalker.ts
- packages/scenario/src/lib/createSystemScenario.ts
- packages/scenario/src/lib/matchers.ts
- packages/scenario/src/lib/types/request.ts
- packages/scenario/src/lib/types/salute.ts
- packages/scenario/src/lib/types/systemMessage.ts
Closes #20 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.33.0-canary.41.4468419040.0
npm install @salutejs/recognizer-string-similarity@0.33.0-canary.41.4468419040.0
npm install @salutejs/scenario@0.33.0-canary.41.4468419040.0
npm install @salutejs/storage-adapter-firebase@0.33.0-canary.41.4468419040.0
npm install @salutejs/storage-adapter-memory@0.33.0-canary.41.4468419040.0
yarn add @salutejs/recognizer-smartapp-brain@0.33.0-canary.41.4468419040.0
yarn add @salutejs/recognizer-string-similarity@0.33.0-canary.41.4468419040.0
yarn add @salutejs/scenario@0.33.0-canary.41.4468419040.0
yarn add …
```
> Поддержка server_action.action_id

- packages/scenario/src/lib/smartpay.ts
Closes #44
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.33.1-canary.45.4616383526.0
npm install @salutejs/recognizer-string-similarity@0.33.1-canary.45.4616383526.0
npm install @salutejs/scenario@0.33.1-canary.45.4616383526.0
npm install @salutejs/storage-adapter-firebase@0.33.1-canary.45.4616383526.0
npm install @salutejs/storage-adapter-memory@0.33.1-canary.45.4616383526.0
yarn add @salutejs/recognizer-smartapp-brain@0.33.1-canary.45.4616383526.0
yarn add @salutejs/recognizer-string-similarity@0.33.1-canary.45.4616383526.0
yarn add @salutejs/scenario@0.33.1-canary.45.4616383526.0
yarn add …
```
> Изменить хост smartpay

- packages/scenario/src/lib/smartpay.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.33.2-canary.46.4628329709.0
npm install @salutejs/recognizer-string-similarity@0.33.2-canary.46.4628329709.0
npm install @salutejs/scenario@0.33.2-canary.46.4628329709.0
npm install @salutejs/storage-adapter-firebase@0.33.2-canary.46.4628329709.0
npm install @salutejs/storage-adapter-memory@0.33.2-canary.46.4628329709.0
yarn add @salutejs/recognizer-smartapp-brain@0.33.2-canary.46.4628329709.0
yarn add @salutejs/recognizer-string-similarity@0.33.2-canary.46.4628329709.0
yarn add @salutejs/scenario@0.33.2-canary.46.4628329709.0
yarn add …
```
> хост смартпей

- packages/scenario/src/lib/createScenarioWalker.ts
Closes #43 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.33.3-canary.47.4657100045.0
npm install @salutejs/recognizer-string-similarity@0.33.3-canary.47.4657100045.0
npm install @salutejs/scenario@0.33.3-canary.47.4657100045.0
npm install @salutejs/storage-adapter-firebase@0.33.3-canary.47.4657100045.0
npm install @salutejs/storage-adapter-memory@0.33.3-canary.47.4657100045.0
yarn add @salutejs/recognizer-smartapp-brain@0.33.3-canary.47.4657100045.0
yarn add @salutejs/recognizer-string-similarity@0.33.3-canary.47.4657100045.0
yarn add @salutejs/scenario@0.33.3-canary.47.4657100045.0
yarn add …
```
> fix: Не срабатывает RUN_APP

- examples/echo/src/pages/index.tsx
- examples/todo/package-lock.json
- examples/todo/package.json
- examples/todo/src/Components/GlobalStyles.tsx
- examples/todo/src/pages/index.tsx
- packages/scenario/src/lib/createSystemScenario.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.34.0-canary.50.4869634955.0
npm install @salutejs/recognizer-string-similarity@0.34.0-canary.50.4869634955.0
npm install @salutejs/scenario@0.34.0-canary.50.4869634955.0
npm install @salutejs/storage-adapter-firebase@0.34.0-canary.50.4869634955.0
npm install @salutejs/storage-adapter-memory@0.34.0-canary.50.4869634955.0
yarn add @salutejs/recognizer-smartapp-brain@0.34.0-canary.50.4869634955.0
yarn add @salutejs/recognizer-string-similarity@0.34.0-canary.50.4869634955.0
yarn add @salutejs/scenario@0.34.0-canary.50.4869634955.0
yarn add …
```
> Дженерики в createSystemScenario

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.36.0-canary.52.5077441372.0
npm install @salutejs/recognizer-string-similarity@0.36.0-canary.52.5077441372.0
npm install @salutejs/scenario@0.36.0-canary.52.5077441372.0
npm install @salutejs/storage-adapter-firebase@0.36.0-canary.52.5077441372.0
npm install @salutejs/storage-adapter-memory@0.36.0-canary.52.5077441372.0
yarn add @salutejs/recognizer-smartapp-brain@0.36.0-canary.52.5077441372.0
yarn add @salutejs/recognizer-string-similarity@0.36.0-canary.52.5077441372.0
yarn add @salutejs/scenario@0.36.0-canary.52.5077441372.0
yarn add …
```
> Заголовок для активной карточки оператора

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.37.0-canary.54.5569910767.0
npm install @salutejs/recognizer-string-similarity@0.37.0-canary.54.5569910767.0
npm install @salutejs/scenario@0.37.0-canary.54.5569910767.0
npm install @salutejs/storage-adapter-firebase@0.37.0-canary.54.5569910767.0
npm install @salutejs/storage-adapter-memory@0.37.0-canary.54.5569910767.0
yarn add @salutejs/recognizer-smartapp-brain@0.37.0-canary.54.5569910767.0
yarn add @salutejs/recognizer-string-similarity@0.37.0-canary.54.5569910767.0
yarn add @salutejs/scenario@0.37.0-canary.54.5569910767.0
yarn add …
```
> feat: Добавлены виджеты в SystemMessage

- packages/storage-adapter-firebase/package-lock.json
- packages/storage-adapter-firebase/package.json
- packages/storage-adapter-firebase/tsconfig.json
<details>
<br />
```bash
npm install @salutejs/storage-adapter-firebase@0.37.1-canary.59.5794634433.0
yarn add @salutejs/storage-adapter-firebase@0.37.1-canary.59.5794634433.0
```
</details>
> chore: обновление firebase-admin

- packages/scenario/package-lock.json
- packages/scenario/package.json
- packages/scenario/src/lib/smartpush.ts
closes #73 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.37.1-canary.74.5806006936.0
npm install @salutejs/recognizer-string-similarity@0.37.1-canary.74.5806006936.0
npm install @salutejs/scenario@0.37.1-canary.74.5806006936.0
npm install @salutejs/storage-adapter-firebase@0.37.1-canary.74.5806006936.0
npm install @salutejs/storage-adapter-memory@0.37.1-canary.74.5806006936.0
yarn add @salutejs/recognizer-smartapp-brain@0.37.1-canary.74.5806006936.0
yarn add @salutejs/recognizer-string-similarity@0.37.1-canary.74.5806006936.0
yarn add @salutejs/scenario@0.37.1-canary.74.5806006936.0
yarn add …
```
> chore: использовать либу uuid

- examples/todo/global.d.ts
- examples/todo/next.config.js
- examples/todo/package-lock.json
- examples/todo/package.json
- examples/todo/src/pages/_app.tsx
- examples/todo/src/pages/_document.tsx
- examples/todo/src/pages/index.tsx
- examples/todo/src/utils/assistant.ts
- examples/todo/tsconfig.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.37.1-canary.76.5809395834.0
npm install @salutejs/recognizer-string-similarity@0.37.1-canary.76.5809395834.0
npm install @salutejs/scenario@0.37.1-canary.76.5809395834.0
npm install @salutejs/storage-adapter-firebase@0.37.1-canary.76.5809395834.0
npm install @salutejs/storage-adapter-memory@0.37.1-canary.76.5809395834.0
yarn add @salutejs/recognizer-smartapp-brain@0.37.1-canary.76.5809395834.0
yarn add @salutejs/recognizer-string-similarity@0.37.1-canary.76.5809395834.0
yarn add @salutejs/scenario@0.37.1-canary.76.5809395834.0
yarn add …
```
> chore: актуализирован examples/todo

- examples/todo/package-lock.json
- examples/todo/package.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.37.1-canary.78.5818807710.0
npm install @salutejs/recognizer-string-similarity@0.37.1-canary.78.5818807710.0
npm install @salutejs/scenario@0.37.1-canary.78.5818807710.0
npm install @salutejs/storage-adapter-firebase@0.37.1-canary.78.5818807710.0
npm install @salutejs/storage-adapter-memory@0.37.1-canary.78.5818807710.0
yarn add @salutejs/recognizer-smartapp-brain@0.37.1-canary.78.5818807710.0
yarn add @salutejs/recognizer-string-similarity@0.37.1-canary.78.5818807710.0
yarn add @salutejs/scenario@0.37.1-canary.78.5818807710.0
yarn add …
```
> chore: удален publish в examples/todo

- examples/todo/package-lock.json
- packages/scenario/src/lib/types/request.ts
closes #86 
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.37.1-canary.87.5820595989.0
npm install @salutejs/recognizer-string-similarity@0.37.1-canary.87.5820595989.0
npm install @salutejs/scenario@0.37.1-canary.87.5820595989.0
npm install @salutejs/storage-adapter-firebase@0.37.1-canary.87.5820595989.0
npm install @salutejs/storage-adapter-memory@0.37.1-canary.87.5820595989.0
yarn add @salutejs/recognizer-smartapp-brain@0.37.1-canary.87.5820595989.0
yarn add @salutejs/recognizer-string-similarity@0.37.1-canary.87.5820595989.0
yarn add @salutejs/scenario@0.37.1-canary.87.5820595989.0
yarn add …
```
> fix: исправлен NLPRequestTPD

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.38.0-canary.88.5865122927.0
npm install @salutejs/recognizer-string-similarity@0.38.0-canary.88.5865122927.0
npm install @salutejs/scenario@0.38.0-canary.88.5865122927.0
npm install @salutejs/storage-adapter-firebase@0.38.0-canary.88.5865122927.0
npm install @salutejs/storage-adapter-memory@0.38.0-canary.88.5865122927.0
yarn add @salutejs/recognizer-smartapp-brain@0.38.0-canary.88.5865122927.0
yarn add @salutejs/recognizer-string-similarity@0.38.0-canary.88.5865122927.0
yarn add @salutejs/scenario@0.38.0-canary.88.5865122927.0
yarn add …
```
> feat: В TextView добавлен признак чувствительной информации

- packages/scenario/src/lib/types/response.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.38.1-canary.89.5950991243.0
npm install @salutejs/recognizer-string-similarity@0.38.1-canary.89.5950991243.0
npm install @salutejs/scenario@0.38.1-canary.89.5950991243.0
npm install @salutejs/storage-adapter-firebase@0.38.1-canary.89.5950991243.0
npm install @salutejs/storage-adapter-memory@0.38.1-canary.89.5950991243.0
yarn add @salutejs/recognizer-smartapp-brain@0.38.1-canary.89.5950991243.0
yarn add @salutejs/recognizer-string-similarity@0.38.1-canary.89.5950991243.0
yarn add @salutejs/scenario@0.38.1-canary.89.5950991243.0
yarn add …
```
> fix: Актуализировать NLPRequestTPD

- packages/scenario/src/lib/types/payment.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.39.0-canary.92.6069784947.0
npm install @salutejs/recognizer-string-similarity@0.39.0-canary.92.6069784947.0
npm install @salutejs/scenario@0.39.0-canary.92.6069784947.0
npm install @salutejs/storage-adapter-firebase@0.39.0-canary.92.6069784947.0
npm install @salutejs/storage-adapter-memory@0.39.0-canary.92.6069784947.0
yarn add @salutejs/recognizer-smartapp-brain@0.39.0-canary.92.6069784947.0
yarn add @salutejs/recognizer-string-similarity@0.39.0-canary.92.6069784947.0
yarn add @salutejs/scenario@0.39.0-canary.92.6069784947.0
yarn add …
```
> feat: Передавать user_id при создании платежки

- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@0.40.0-canary.110.6639991729.0
npm install @salutejs/recognizer-string-similarity@0.40.0-canary.110.6639991729.0
npm install @salutejs/scenario@0.40.0-canary.110.6639991729.0
npm install @salutejs/storage-adapter-firebase@0.40.0-canary.110.6639991729.0
npm install @salutejs/storage-adapter-memory@0.40.0-canary.110.6639991729.0
yarn add @salutejs/recognizer-smartapp-brain@0.40.0-canary.110.6639991729.0
yarn add @salutejs/recognizer-string-similarity@0.40.0-canary.110.6639991729.0
yarn add @salutejs/scenario@0.40.0-canary.110.6639991729.0
yarn add …
```
> feat: Добавление иконки total в LocalImageIdentificator

- examples/todo/package-lock.json
- examples/todo/package.json
- packages/storage-adapter-firebase/package-lock.json
- packages/storage-adapter-firebase/package.json
<details>
<br />
```bash
npm install @salutejs/storage-adapter-firebase@0.40.1-canary.113.7045906850.0
yarn add @salutejs/storage-adapter-firebase@0.40.1-canary.113.7045906850.0
```
</details>
> chore: bump firebase packages

- .commitlintrc.json
- packages/scenario/src/lib/types/storage.ts
- packages/storage-adapter-memory/src/index.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.0.0-canary.117.7113181050.0
npm install @salutejs/recognizer-string-similarity@1.0.0-canary.117.7113181050.0
npm install @salutejs/scenario@1.0.0-canary.117.7113181050.0
npm install @salutejs/storage-adapter-firebase@1.0.0-canary.117.7113181050.0
npm install @salutejs/storage-adapter-memory@1.0.0-canary.117.7113181050.0
yarn add @salutejs/recognizer-smartapp-brain@1.0.0-canary.117.7113181050.0
yarn add @salutejs/recognizer-string-similarity@1.0.0-canary.117.7113181050.0
yarn add @salutejs/scenario@1.0.0-canary.117.7113181050.0
yarn add …
```
> BREAKING: Добавлена автовалидация жизни сессии в StorageAdapter

- examples/todo/package-lock.json
- examples/todo/package.json
- examples/todo/src/scenario/handlers.ts
- examples/todo/src/scenario/scenario.ts
- examples/todo/src/scenario/types.ts
- packages/scenario/src/lib/createSaluteRequest.ts
- packages/scenario/src/lib/createScenarioWalker.ts
- packages/scenario/src/lib/createSystemScenario.ts
- packages/scenario/src/lib/createUserScenario.ts
- packages/scenario/src/lib/types/salute.ts
- packages/scenario/src/lib/types/storage.ts
- packages/storage-adapter-memory/src/index.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.0.1-canary.118.7258460566.0
npm install @salutejs/recognizer-string-similarity@1.0.1-canary.118.7258460566.0
npm install @salutejs/scenario@1.0.1-canary.118.7258460566.0
npm install @salutejs/storage-adapter-firebase@1.0.1-canary.118.7258460566.0
npm install @salutejs/storage-adapter-memory@1.0.1-canary.118.7258460566.0
yarn add @salutejs/recognizer-smartapp-brain@1.0.1-canary.118.7258460566.0
yarn add @salutejs/recognizer-string-similarity@1.0.1-canary.118.7258460566.0
yarn add @salutejs/scenario@1.0.1-canary.118.7258460566.0
yarn add …
```
> fix: Исправлены типы в Scenario

- examples/echo/package-lock.json
- examples/echo/package.json
- examples/todo/package-lock.json
- examples/todo/package.json
- examples/todo/src/Components/GlobalStyles.tsx
- packages/scenario/src/lib/i18n.spec.ts
- packages/scenario/src/lib/types/systemMessage.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.0.2-canary.125.7883194222.0
npm install @salutejs/recognizer-string-similarity@1.0.2-canary.125.7883194222.0
npm install @salutejs/scenario@1.0.2-canary.125.7883194222.0
npm install @salutejs/storage-adapter-firebase@1.0.2-canary.125.7883194222.0
npm install @salutejs/storage-adapter-memory@1.0.2-canary.125.7883194222.0
yarn add @salutejs/recognizer-smartapp-brain@1.0.2-canary.125.7883194222.0
yarn add @salutejs/recognizer-string-similarity@1.0.2-canary.125.7883194222.0
yarn add @salutejs/scenario@1.0.2-canary.125.7883194222.0
yarn add …
```
> fix: athena вместо eva

- packages/scenario/src/lib/createSaluteResponse.ts
- packages/scenario/src/lib/types/salute.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.1.0-canary.127.8047874542.0
npm install @salutejs/recognizer-string-similarity@1.1.0-canary.127.8047874542.0
npm install @salutejs/scenario@1.1.0-canary.127.8047874542.0
npm install @salutejs/storage-adapter-firebase@1.1.0-canary.127.8047874542.0
npm install @salutejs/storage-adapter-memory@1.1.0-canary.127.8047874542.0
yarn add @salutejs/recognizer-smartapp-brain@1.1.0-canary.127.8047874542.0
yarn add @salutejs/recognizer-string-similarity@1.1.0-canary.127.8047874542.0
yarn add @salutejs/scenario@1.1.0-canary.127.8047874542.0
yarn add …
```
> feat: поддержка кастомных мессаджей в ответе сценария

- packages/scenario/src/lib/types/systemMessageOriginal.ts
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.3.0-canary.146.9794629911.0
npm install @salutejs/recognizer-string-similarity@1.3.0-canary.146.9794629911.0
npm install @salutejs/scenario@1.3.0-canary.146.9794629911.0
npm install @salutejs/storage-adapter-firebase@1.3.0-canary.146.9794629911.0
npm install @salutejs/storage-adapter-memory@1.3.0-canary.146.9794629911.0
yarn add @salutejs/recognizer-smartapp-brain@1.3.0-canary.146.9794629911.0
yarn add @salutejs/recognizer-string-similarity@1.3.0-canary.146.9794629911.0
yarn add @salutejs/scenario@1.3.0-canary.146.9794629911.0
yarn add …
```
> feat: обновил типы для plasma_typeface

- .github/workflows/semgrep.yml
- packages/recognizer-smartapp-brain/package-lock.json
- packages/recognizer-smartapp-brain/package.json
- packages/scenario/package-lock.json
- packages/scenario/package.json
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.3.1-canary.152.10382788018.0
npm install @salutejs/recognizer-string-similarity@1.3.1-canary.152.10382788018.0
npm install @salutejs/scenario@1.3.1-canary.152.10382788018.0
npm install @salutejs/storage-adapter-firebase@1.3.1-canary.152.10382788018.0
npm install @salutejs/storage-adapter-memory@1.3.1-canary.152.10382788018.0
yarn add @salutejs/recognizer-smartapp-brain@1.3.1-canary.152.10382788018.0
yarn add @salutejs/recognizer-string-similarity@1.3.1-canary.152.10382788018.0
yarn add @salutejs/scenario@1.3.1-canary.152.10382788018.0
yarn add …
```
> Deps fixes

- .github/workflows/semgrep.yml
<details>
<br />
```bash
npm install @salutejs/recognizer-smartapp-brain@1.3.1-canary.153.10382883274.0
npm install @salutejs/recognizer-string-similarity@1.3.1-canary.153.10382883274.0
npm install @salutejs/scenario@1.3.1-canary.153.10382883274.0
npm install @salutejs/storage-adapter-firebase@1.3.1-canary.153.10382883274.0
npm install @salutejs/storage-adapter-memory@1.3.1-canary.153.10382883274.0
yarn add @salutejs/recognizer-smartapp-brain@1.3.1-canary.153.10382883274.0
yarn add @salutejs/recognizer-string-similarity@1.3.1-canary.153.10382883274.0
yarn add @salutejs/scenario@1.3.1-canary.153.10382883274.0
yarn add …
```
> chore: update semgrep action 2
